baseURL = "https://codeandbeyond.rocks/"
languageCode = "en-US"
title = "Code && Beyond"
copyright = "Alexander Sulim and Pablo Vicente"

[sitemap]
priority = 0.5

[[menu.main]]
identifier = "episodes"
title = "Episodes"
name = "Episodes"
url = "/episodes/"

[[menu.main]]
identifier = "about"
title = "About"
name = "About"
url = "/about/"

[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      X-Frame-Options = "DENY"
      Content-Security-Policy = """\
                                default-src 'none'; \
                                base-uri 'self'; \
                                form-action 'self'; \
                                connect-src 'self' https://plausible.io; \
                                font-src 'self'; \
                                frame-src 'self' https://www.youtube-nocookie.com; \
                                img-src 'self' data:; \
                                manifest-src 'self'; \
                                media-src 'self' https://anchor.fm https://d3ctxlq1ktw2nl.cloudfront.net; \
                                object-src 'none'; \
                                script-src 'self' https://plausible.io; \
                                style-src 'self' 'unsafe-inline'; \
                                frame-ancestors 'none'\
                                """
